### ISSUE TITLE
Forager 1.2: NVIDIA power not captured

### ISSUE THREAD

**Issue by eMTee72** [yuzi-co/Forager#23] opened 2018-05-13 16:57 UTC
Codebase grabbed on 9-May (v1.1) was showing the Watt for my NVIDIA cards fine, but v1.2 (grabbed on 13-May) does not show the wattage anymore… .

**Comment by yuzi-co** [comment] 2018-05-13 17:03
Are you using with or without Afterburner?

**Comment by eMTee72** [comment] 2018-05-13 17:32
With AB 4.5.0.12819

**Comment by eMTee72** [comment] 2018-05-13 18:29
I guess: yes...

```
SrcName          SrcUnits LocalizedSrcName LocalizedSrcUnits RecommendedFormat    Data MinLimit MaxLimit Flags        GPU
-------          -------- ---------------- ----------------- -----------------    ---- -------- -------- -----        ---
GPU1 temperature °C       GPU1 temperature °C                %.0f                   60        0      100  None          0
GPU2 temperature °C       GPU2 temperature °C                %.0f                   58        0      100  None          1
GPU3 temperature °C       GPU3 temperature °C                %.0f                   57        0      100  None          2
GPU4 temperature °C       GPU4 temperature °C                %.0f                   61        0      100  None          3
GPU5 temperature °C       GPU5 temperature °C                %.0f                   59        0      100  None          4
GPU6 temperature °C       GPU6 temperature °C                %.0f                   56        0      100  None          5
GPU7 temperature °C       GPU7 temperature °C                %.0f                   53        0      100  None          6
GPU8 temperature °C       GPU8 temperature °C                %.0f                   53        0      100  None          7
GPU1 usage       %        GPU1 usage       %                 %.0f                   98        0      100  None          0
GPU2 usage       %        GPU2 usage       %                 %.0f                   98        0      100  None          1
GPU3 usage       %        GPU3 usage       %                 %.0f                  100        0      100  None          2
GPU4 usage       %        GPU4 usage       %                 %.0f                   99        0      100  None          3
GPU5 usage       %        GPU5 usage       %                 %.0f                  100        0      100  None          4
GPU6 usage       %        GPU6 usage       %                 %.0f                   99        0      100  None          5
GPU7 usage       %        GPU7 usage       %                 %.0f                   99        0      100  None          6
GPU8 usage       %        GPU8 usage       %                 %.0f                  100        0      100  None          7
GPU1 power       %        GPU1 power       %                 %.0f                   67        0      150  None          0
GPU2 power       %        GPU2 power       %                 %.0f                   65        0      150  None          1
GPU3 power       %        GPU3 power       %                 %.0f                   64        0      150  None          2
GPU4 power       %        GPU4 power       %                 %.0f                   70        0      150  None          3
GPU5 power       %        GPU5 power       %                 %.0f                   65        0      150  None          4
GPU6 power       %        GPU6 power       %                 %.0f                   69        0      150  None          5
GPU7 power       %        GPU7 power       %                 %.0f                   67        0      150  None          6
GPU8 power       %        GPU8 power       %                 %.0f                   63        0      150  None          7
CPU power        W        CPU power        W                 %.1f              5.78677        0      200  None 4294967295

```

**Comment by yuzi-co** [comment] 2018-05-14 20:51
1. Please verify if "Afterburner = ENABLED" is uncommented in config
2. If its not, then you are not using AB integration and there was an error that should be now fixed in master

**Comment by eMTee72** [comment] 2018-05-17 18:19
Grabbed today's code, added AFTERBURNER = ENABLED to config and Watt for NVIDIA cards is displayed again!
Benchmarking the N-miners with the missing Watt values now.

PS: something interesting I noticed on AMD-cards with this release --> my RX570 officially consumes 150W. In AB I configured it with a Power Limit of -20%, meaning 120W. With the codebase of 3 days ago (and older), Forager indicated a 120W AMD GPU usage… all the time. After applying the codebase of today, it varies (e.g between 95W and 120W). So fingers crossed now that these new values are correct, as it means more Profit!  ;-)

**Comment by yuzi-co** [comment] 2018-05-17 18:25
Once you have enabled Afterburner, you get real consumption data.
Without AB, its only an estimation (based on max TDP * GPU utilization)

With AB, You can define Powerlimits for AMD as well (without AB only Nvidia) using GpuGroups and let Forager benchmark them instead of setting it manually in AB ;)

**Comment by eMTee72** [comment] 2018-05-17 18:39
I've been playing with the Powerlimits of the GPUGroups, but back then I wasn't convinced by it.

If I recall correctly, this is what was done back then:
Assume: PL's on 70, 80, 90
Between Algo X, Y and Z, Algo X is the most favorable. I belive back then that was measured as Fiat/Day (and not Profit/Day). So Algo X with PL 70 was then benchmarked against Algo X with PL 80 and Algo X with PL 90. Obviously, PL 90 was always morefavourable than PL 70 (just because of the headroom).
I might have been wrong with my observations (or how I recall it), but when giving it some thoughts now I would measure this in Hashes/Watt. With your AB integration you now should be perfectly able to do so, right? Only then PL's start to make sense, not?

**Comment by yuzi-co** [comment] 2018-05-17 18:52
It's sorted by Profit/Day, the highest Revenue minus power Cost (make sure you define ElectricityCost in config).

It doesn't look for the most efficient and will only pick lower powerlimit in case where the higher power consumption does not cover the additional revenue.

It may not be worth it to use several powerlimits, but you can define the one you use in the config instead of setting it in AB, just as a convenience

**Comment by yuzi-co** [comment] 2018-05-18 18:18
closing since the issue is resolved

**Closed as completed by yuzi-co** 2018-05-18 18:18 UTC
