### ISSUE TITLE
Miner speed 1000x higher than it is.

### ISSUE THREAD

**Issue by VukaKun** [yuzi-co/Forager#6] opened 2018-04-07 00:03 UTC
Hey man, I love your fork and I've been using it as a basis for my own version. The thing is, several miner-algo combinations seem to report kh/s instead of h/s and I can't seem to find the relevant code. Do you know what might be causing such issues?

**Comment by yuzi-co** [comment] 2018-04-07 10:05
Which miners exacly? Can you post an example?

In miner file definition, there is "api" field
if they use same api type, maybe there is an error in api definition for in include.ps1
I believe all CPU/AMD miners are accurate, but since I don't have NVidia hardware, I can't verify those

**Comment by VukaKun** [comment] 2018-04-07 10:27
Hmmm, yeah, it might be NVidia related, since I don't have any AMD hardware. But there are also some issues with the CPU speeds. The problems started about a week ago, but unfortunately, I didn't take note of the exact changes that did that. But I believe it started after I synced some code from your repository. I provided some screenshots, so you can take a look at it yourself. I'll see if I can do anything myself in the meantime, thanks for pointing out the API field in miner files.

![1](https://user-images.githubusercontent.com/27901969/38453975-f09fcd38-3a5e-11e8-9ff8-b74e31b31e9b.png)
![2](https://user-images.githubusercontent.com/27901969/38453976-f3ba0d6c-3a5e-11e8-8cfa-c1867ea3ee86.png)
![3](https://user-images.githubusercontent.com/27901969/38453977-f6b447da-3a5e-11e8-8a25-ecb333709326.png)

**Comment by yuzi-co** [comment] 2018-04-07 12:32
I believe it's caused by decimal separator defined in system locale ('.' vs ',')
when the CSV files that store the benchmark data are imported, it incorrectly parses decimal digits

I'm looking into a way to fix it

**Comment by yuzi-co** [comment] 2018-04-07 13:29
problem was that export-csv was saving numbers in system locale, but loading them as en-US
fixed in latest commit by enforcing en-US locale for MegaMiner process

the side effect, unfortunately, is that you will need to re-benchmark, since it will fail loading the existing CSVs

**Comment by VukaKun** [comment] 2018-04-07 15:27
Ah, unbelievable! But you're right, nice catch! Croatian locale is so ridiculous, it **does** use the decimal comma instead of a point. Of course, no one actually uses it in practice, but it's _officially_ the correct way.

**Comment by VukaKun** [comment] 2018-04-07 15:38
I modified the number format for the entire system and I'll rebenchmark everything, should do the trick.

**Closed as completed** 2018-04-11 14:53 UTC
